## makeCacheMatrix can assign a value to an object in an environment and 
## store this value in cache.cacheSolve checks cache for inversed matrix  
## generated by makeChacheMatrix, 
## if not, it inverses the matrix.
## functions do
## set the value of matrix
## get the value of matrix
## setcache: set inversed matrix
## getcache: get inversed matrix

## makeCacheMatrix function creates a matrix and inverses the matrix,
## then caches the inversed matrix.

makeCacheMatrix <- function(x = matrix()) {
   m <- NULL
  set <- function(y) {
    x <<- y
    m <- NULL
  }
  get <- function() x
  setcache <- function(solve) m <<- solve
  getcache <- function() m
  list(set = set, get = get,
       setcache = setcache,
       getcache = getcache)

}


## cacheSolve function first checks the matrix has already been inversed.
## If yes, it gets the inversed matrix from the cache.
## If not, it inverses the matrix and set the inversed matrix to cache.

## cacheSolve function first checks the matrix has already been inversed.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getcache()
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setcache(m)
  m
}
